POST https://us-central1-fir-project1-8dac5.cloudfunctions.net/helloWorld
Content-Type: application/json

{
    "name1" : "value1",
    "name2" : "value2",
    "name3" : "value3",
    "name4" : "value4",
    "name5" : "value5"
}


POST https://us-central1-fir-project1-8dac5.cloudfunctions.net/saveContact
Content-Type: application/json

{
    "first_name" : "Sammy",
    "last_name" : "Appleseed",
    "phone" : "321-654-7891",
    "handled" : false
}

POST https://us-central1-fir-project1-8dac5.cloudfunctions.net/saveContact
Content-Type: application/json

{
    "full_name" : "Appleseed, Tommy",
    "phone" : "321-654-7891",
    "handled" : false
}

GET https://us-central1-fir-project1-8dac5.cloudfunctions.net/getNewContacts
Content-Type: application/json

